import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const categories = { missing_in_dropbox: 'Missing in Dropbox', additional_in_dropbox: 'Additional Dropbox items', type_conflict: 'Type conflicts', size_mismatch: 'Size mismatches' };
const APP_VERSION = __APP_VERSION__;

function App() {
  const [settings, setSettings] = useState(null); const [system, setSystem] = useState(null); const [scans, setScans] = useState([]); const [projects, setProjects] = useState([]); const [search, setSearch] = useState(''); const [detail, setDetail] = useState(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const load = async () => { const [s, x, p, systemStatus] = await Promise.all([get('/api/settings'), get('/api/scans'), get('/api/projects').catch(() => []), get('/api/status')]); setSettings(s); setScans(x); setProjects(p); setSystem(systemStatus); };
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    if (params.get('dropbox') === 'error') {
      setMessage(params.get('message') || 'Dropbox connection was not completed.');
      window.history.replaceState({}, '', window.location.pathname);
    }
  }, []);
  useEffect(() => { load(); const timer = setInterval(load, 3000); return () => clearInterval(timer); }, []);
  const visible = useMemo(() => scans.filter(s => s.project_name.toLowerCase().includes(search.toLowerCase())), [scans, search]);
  const processing = visible.filter(s => ['queued', 'running', 'paused'].includes(s.status)); const needsAttention = visible.filter(s => !s.remote_only && !['queued', 'running', 'paused'].includes(s.status) && (classify(s) === 'attention' || s.status === 'incomplete')); const remoteOnly = visible.filter(s => s.remote_only); const good = visible.filter(s => !s.remote_only && !['queued', 'running', 'paused'].includes(s.status) && classify(s) !== 'attention' && s.status !== 'incomplete');
  if (!settings || !system) return <main className="loading">Loading Vault Compare…</main>;
  const save = async data => { setBusy(true); try { await send('/api/settings', 'PUT', data); setMessage('Saved.'); await load(); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  const start = async names => { setBusy(true); try { const result = await send('/api/scans', 'POST', { projectNames: names }); setMessage(`${result.queued} project${result.queued === 1 ? '' : 's'} queued.`); await load(); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  return <main>
    <header><div><span className="eyebrow">LOCAL → DROPBOX</span><h1>Vault Compare</h1></div><div className="header-actions"><input aria-label="Search projects" value={search} onChange={e => setSearch(e.target.value)} placeholder="Search projects"/><button disabled={busy} onClick={async () => { await send(system.queuePaused ? '/api/queue/resume' : '/api/queue/pause', 'POST', {}); await load(); }}>{system.queuePaused ? 'Resume processing' : 'Pause processing'}</button><button className="primary" disabled={busy || !settings.connected} onClick={() => start(null)}>Scan all</button></div></header>
    {message && <div className="toast">{message}<button onClick={() => setMessage('')}>×</button></div>}
    {!settings.connected ? <Setup settings={settings} save={save} busy={busy} setMessage={setMessage} load={load}/> : <>
      <section className="access-status"><AccessStatus label="Vault" item={system.health?.vault} stats={system.health?.stats?.vault} projects={system.health?.stats?.projects}/><AccessStatus label="Dropbox" item={system.health?.dropbox} stats={system.health?.stats?.dropbox} projects={system.health?.stats?.projects}/></section>
      <section className="summary"><Metric label="Projects" value={projects.length}/><Metric label="Needs attention" value={needsAttention.length} tone={needsAttention.length ? 'bad' : ''}/><Metric label="Matched" value={good.filter(x => x.status === 'complete').length}/><Metric label="Queue" value={scans.filter(x => ['queued', 'running'].includes(x.status)).length}/></section>
      <section className="toolbar"><span>{settings.remoteRoot || '/'} on Dropbox</span><button disabled={busy} onClick={() => setDetail({ settings: true })}>Settings</button></section>
      <ProjectSection title={system.queuePaused ? 'Processing paused' : 'Processing'} empty="No projects are waiting or scanning." scans={processing} onScan={name => start([name])} onDetail={setDetail}/>
      <ProjectSection title="Needs attention" empty="No current mismatches." scans={needsAttention} onScan={name => start([name])} onDetail={setDetail}/>
      <ProjectSection title="Additional Dropbox projects" quiet empty="No additional Dropbox projects found." scans={remoteOnly} onScan={name => start([name])} onDetail={setDetail}/>
      <ProjectSection title="Matched & additions" quiet empty="No completed matching projects yet." scans={good} onScan={name => start([name])} onDetail={setDetail}/>
    </>}
    <footer>Vault Compare <span>v{APP_VERSION}</span></footer>
    {detail?.settings && <SettingsModal settings={settings} save={save} close={() => setDetail(null)} setMessage={setMessage} load={load}/>} {detail?.browser && <BrowserModal scan={detail} close={() => setDetail(null)}/>} {detail?.id && <DetailModal scan={detail} close={() => setDetail(null)}/>}
  </main>;
}

function Setup({ settings, busy, setMessage, load }) {
  const [accessToken, setAccessToken] = useState(''); const [remoteRoot, setRemoteRoot] = useState(settings.remoteRoot); const connect = async () => { try { await send('/api/dropbox/access-token', 'POST', { accessToken, remoteRoot, historyLimit: 5 }); setMessage('Dropbox access token validated and saved.'); await load(); } catch (e) { setMessage(e.message); } };
  return <section className="setup"><span className="eyebrow">SETUP REQUIRED</span><h2>Connect your Dropbox</h2><p>This app only reads <code>{settings.vaultRoot}</code>, which Docker mounts from <code>T:\vault</code> as read-only.</p><label>Generated Dropbox access token<input type="password" value={accessToken} onChange={e => setAccessToken(e.target.value)} placeholder="Paste generated access token" autoComplete="off"/></label><label>Dropbox mirror root<input value={remoteRoot} onChange={e => setRemoteRoot(e.target.value)} placeholder="/Vault mirror"/></label><p className="hint">In the <a href="https://www.dropbox.com/developers/apps" target="_blank">Dropbox App Console</a>, use a Full Dropbox app with <code>files.metadata.read</code> enabled, then click <strong>Generate</strong> in OAuth 2. Paste the token above. The app validates the token and selected root before saving it.</p><button className="primary wide" disabled={busy || !accessToken.trim()} onClick={connect}>Validate & save token</button></section>;
}
function SettingsModal({ settings, save, close, setMessage, load }) {
  const [appKey, setAppKey] = useState(settings.appKey); const [remoteRoot, setRemoteRoot] = useState(settings.remoteRoot); const [historyLimit, setHistoryLimit] = useState(settings.historyLimit); const [bundle, setBundle] = useState(''); const [accessToken, setAccessToken] = useState('');
  const exportBundle = async () => { const r = await get('/api/connection/export'); setBundle(r.bundle); navigator.clipboard?.writeText(r.bundle); setMessage('Connection bundle copied.'); };
  const importBundle = async () => { try { await send('/api/connection/import', 'POST', { bundle }); setMessage('Connection imported.'); await load(); close(); } catch (e) { setMessage(e.message); } };
  return <Modal title="Settings" close={close}><label>Dropbox mirror root<input value={remoteRoot} onChange={e => setRemoteRoot(e.target.value)}/></label><label>History to retain<input type="number" min="1" max="100" value={historyLimit} onChange={e => setHistoryLimit(Number(e.target.value))}/></label><button className="primary" onClick={async () => { await save({ appKey, remoteRoot, historyLimit }); close(); }}>Save settings</button><hr/><h3>Replace generated access token</h3><label>New token<input type="password" value={accessToken} onChange={e => setAccessToken(e.target.value)} placeholder="Paste a newly generated token" autoComplete="off"/></label><button disabled={!accessToken.trim()} onClick={async () => { try { await send('/api/dropbox/access-token', 'POST', { accessToken, remoteRoot, historyLimit }); setMessage('New access token validated and saved.'); await load(); close(); } catch (e) { setMessage(e.message); } }}>Validate & replace token</button><hr/><h3>Transfer Dropbox connection</h3><p className="hint">For your local personal app only. This bundle contains access credentials—treat it like a password.</p><textarea value={bundle} onChange={e => setBundle(e.target.value)} placeholder="Export to copy, or paste a bundle to import"/><div className="row"><button onClick={exportBundle}>Export & copy</button><button onClick={importBundle} disabled={!bundle}>Import bundle</button></div></Modal>;
}
function ProjectSection({ title, scans, empty, quiet, onScan, onDetail }) { return <section className={`projects ${quiet ? 'quiet' : ''}`}><h2>{title}<span>{scans.length}</span></h2>{scans.length ? scans.map(scan => <ProjectRow key={scan.id} scan={scan} onScan={onScan} onDetail={onDetail}/>) : <p className="empty">{empty}</p>}</section>; }
function ProjectRow({ scan, onScan, onDetail }) { const state = classify(scan); const progress = scan.status === 'running' ? (scan.phase === 'local' ? scan.local_done ? 100 : 45 : scan.local_items ? Math.min(99, Math.round(scan.remote_items / scan.local_items * 100)) : 50) : 100; const extra = countCategory(scan, 'additional_in_dropbox'); return <article className={`project ${state} ${scan.status}`}><button className="project-main" onClick={() => scan.status === 'complete' && onDetail({ id: scan.id, name: scan.project_name })}><div><h3>{scan.project_name}</h3><p>{scan.status === 'running' ? `${scan.phase === 'local' ? 'Indexing vault' : 'Listing Dropbox'} · ${formatNumber(scan.phase === 'local' ? scan.local_items : scan.remote_items)} items` : label(scan, extra)}</p></div><div className="numbers"><strong>{scan.status === 'running' ? `${progress}%` : formatNumber(scan.discrepancy_count)}</strong><small>{scan.status === 'running' ? eta(scan) : 'findings'}</small></div></button>{scan.status === 'running' && <div className="progress"><i style={{ width: `${progress}%` }}/></div>}<div className="project-actions"><span className={`badge ${state}`}>{scan.status === 'paused' ? 'Paused' : scan.remote_only ? 'Additional project' : scan.status === 'incomplete' ? 'Incomplete' : state === 'attention' ? 'Mismatch' : extra ? 'Matched + additions' : 'Matched'}</span>{scan.status === 'complete' && <button onClick={() => onDetail({ browser: true, id: scan.id, name: scan.project_name })}>Browse</button>}{!scan.remote_only && <button onClick={() => onScan(scan.project_name)}>Rescan</button>}</div></article>; }
function DetailModal({ scan, close }) { const [data, setData] = useState(null); const [category, setCategory] = useState(''); useEffect(() => { get(`/api/scans/${scan.id}/discrepancies${category ? `?category=${category}` : ''}`).then(setData); }, [scan.id, category]); return <Modal title={scan.name} close={close}>{!data ? <p>Loading findings…</p> : <><div className="tabs"><button className={!category ? 'active' : ''} onClick={() => setCategory('')}>All</button>{data.counts.map(x => <button key={x.category} className={category === x.category ? 'active' : ''} onClick={() => setCategory(x.category)}>{categories[x.category]} <b>{formatNumber(x.count)}</b></button>)}</div><div className="finding-list">{data.rows.map(x => <div className="finding" key={x.id}><span>{categories[x.category]}</span><code>{x.path}</code>{x.category === 'size_mismatch' && <small>{formatBytes(x.local_size)} local · {formatBytes(x.remote_size)} Dropbox</small>}</div>)}{!data.rows.length && <p className="empty">No findings.</p>}</div></>}</Modal>; }
function BrowserModal({ scan, close }) { const [path, setPath] = useState(''); const [local, setLocal] = useState(null); const [remote, setRemote] = useState(null); const [pages, setPages] = useState({ local: 0, remote: 0 });
  useEffect(() => { setLocal(null); setRemote(null); get(`/api/scans/${scan.id}/browser?side=local&path=${encodeURIComponent(path)}&page=${pages.local}`).then(setLocal).catch(e => setLocal({ error: e.message })); get(`/api/scans/${scan.id}/browser?side=remote&path=${encodeURIComponent(path)}&page=${pages.remote}`).then(setRemote).catch(e => setRemote({ error: e.message })); }, [scan.id, path, pages]);
  const open = name => { setPath(path ? `${path}/${name}` : name); setPages({ local: 0, remote: 0 }); }; const up = () => { setPath(path.split('/').slice(0, -1).join('/')); setPages({ local: 0, remote: 0 }); };
  return <Modal title={`${scan.name} · browser`} close={close}><p className="hint">Snapshot from this completed scan. Folders load on demand; each panel shows up to 200 entries.</p><div className="crumbs"><button disabled={!path} onClick={up}>← Up</button><code>/{path}</code></div><div className="browser"><BrowserPanel title="Vault" data={local} open={open} page={pages.local} setPage={p => setPages({ ...pages, local: p })}/><BrowserPanel title="Dropbox" data={remote} open={open} page={pages.remote} setPage={p => setPages({ ...pages, remote: p })}/></div></Modal>; }
function BrowserPanel({ title, data, open, page, setPage }) { return <section className="browser-panel"><h3>{title}</h3>{!data ? <p className="empty">Loading…</p> : data.error ? <p className="empty">{data.error}</p> : <><div className="browser-list">{data.entries.map(entry => <button className="browser-entry" key={`${entry.kind}:${entry.name}`} disabled={entry.kind !== 'folder'} onClick={() => open(entry.name)}><span>{entry.kind === 'folder' ? '▸' : '·'} {entry.name}</span><small>{entry.categories.length ? entry.categories.map(x => categories[x]).join(', ') : entry.kind === 'file' ? formatBytes(entry.size) : 'Folder'}</small></button>)}{!data.entries.length && <p className="empty">Empty folder</p>}</div><div className="pager"><button disabled={!page} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page + 1}</span><button disabled={!data.hasMore} onClick={() => setPage(page + 1)}>Next</button></div></>}</section>; }
function Modal({ title, close, children }) { return <div className="overlay" onMouseDown={close}><section className="modal" onMouseDown={e => e.stopPropagation()}><header><h2>{title}</h2><button className="icon" onClick={close}>×</button></header>{children}</section></div>; }
function Metric({ label, value, tone }) { return <div className={`metric ${tone || ''}`}><span>{label}</span><strong>{formatNumber(value)}</strong></div>; }
function AccessStatus({ label, item, stats, projects }) { const state = item?.state || 'unconfigured'; const text = state === 'ready' ? 'Accessible' : state === 'unconfigured' ? 'Not connected' : 'Unavailable'; const known = stats && projects ? `${formatNumber(stats.items)} items · ${formatBytes(stats.bytes)} known from ${formatNumber(projects)} completed projects` : 'No completed scan data yet.'; return <div className={`access ${state}`} title={item?.detail || ''}><span>{label}</span><strong>{text}</strong><small>{item?.detail}</small><em>{known}</em></div>; }
function classify(s) { if (s.status === 'incomplete') return 'attention'; const n = Number(s.discrepancy_count || 0) - countCategory(s, 'additional_in_dropbox'); return n > 0 ? 'attention' : 'good'; }
function countCategory(s, category) { return Number(s[category] || 0); }
function label(s, extra) { if (s.status === 'queued') return 'Waiting in scan queue'; if (s.status === 'paused') return 'Processing paused'; if (s.status === 'incomplete') return s.error || 'Scan incomplete'; return s.discrepancy_count ? `${formatNumber(s.discrepancy_count)} differences found` : 'No differences found'; }
function eta(s) { if (!s.local_items || s.phase !== 'remote') return 'Estimating…'; const elapsed = Math.max(1, (Date.now() - new Date(s.started_at).getTime()) / 1000); const rate = Math.max(1, s.remote_items / elapsed); return `~${Math.ceil(Math.max(0, s.local_items - s.remote_items) / rate)}s left`; }
const formatNumber = n => new Intl.NumberFormat().format(Number(n || 0)); const formatBytes = n => { if (n == null) return '—'; const units = ['B', 'KB', 'MB', 'GB', 'TB', 'PB']; let value = Number(n); let unit = 0; while (value >= 1024 && unit < units.length - 1) { value /= 1024; unit++; } return `${value.toFixed(value >= 100 || unit === 0 ? 0 : 1)} ${units[unit]}`; };
async function get(url) { const r = await fetch(url); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Request failed'); return d; }
async function send(url, method, body) { const r = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || 'Request failed'); return d; }
createRoot(document.getElementById('root')).render(<App/>);
